-- MySQL Script generated by MySQL Workbench
-- Sun Dec 11 13:55:12 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`StorageLocations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`StorageLocations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `NameOfStorageLocation` VARCHAR(45) NOT NULL,
  `FinanciallyResponsiblePerson` VARCHAR(45) NOT NULL,
  `WarehouseAddress` VARCHAR(45) NOT NULL,
  `ProhibitShipmentsFromTheWarehouse` VARCHAR(45) NOT NULL,
  `ForGoodsAtFixedPricesComingInWholesaleAndSoldThroughRetail` VARCHAR(45) NOT NULL,
  `WarehouseType` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Packers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Packers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `PackerName` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  `Phone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Employees` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `FIO` VARCHAR(45) NOT NULL,
  `Position` VARCHAR(45) NOT NULL,
  `Phone` VARCHAR(45) NOT NULL,
  `Packers_id` INT NOT NULL,
  `StorageLocations_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Employees_Packers1_idx` (`Packers_id` ASC) VISIBLE,
  INDEX `fk_Employees_StorageLocations1_idx` (`StorageLocations_id` ASC) VISIBLE,
  CONSTRAINT `fk_Employees_Packers1`
    FOREIGN KEY (`Packers_id`)
    REFERENCES `mydb`.`Packers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Employees_StorageLocations1`
    FOREIGN KEY (`StorageLocations_id`)
    REFERENCES `mydb`.`StorageLocations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Counterparties`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Counterparties` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Counterpartie` VARCHAR(45) NOT NULL,
  `FullName` VARCHAR(45) NOT NULL,
  `Adress` VARCHAR(45) NULL,
  `Telephone` VARCHAR(45) NOT NULL,
  `MailAdress` VARCHAR(45) NULL,
  `YNP` INT NOT NULL,
  `OKULP` INT NULL,
  `OKPO` INT NULL,
  `OKED` INT NULL,
  `Direсtor` VARCHAR(45) NULL,
  `Employees_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Counterparties_Employees1_idx` (`Employees_id` ASC) VISIBLE,
  CONSTRAINT `fk_Counterparties_Employees1`
    FOREIGN KEY (`Employees_id`)
    REFERENCES `mydb`.`Employees` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Materials`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Materials` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Price` FLOAT NOT NULL,
  `UnitOfMeasurement` VARCHAR(45) NOT NULL,
  `DiscountPrice` FLOAT NOT NULL,
  `StorageLocations_id` INT NOT NULL,
  `Packers_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Materials_StorageLocations1_idx` (`StorageLocations_id` ASC) VISIBLE,
  INDEX `fk_Materials_Packers1_idx` (`Packers_id` ASC) VISIBLE,
  CONSTRAINT `fk_Materials_StorageLocations1`
    FOREIGN KEY (`StorageLocations_id`)
    REFERENCES `mydb`.`StorageLocations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Materials_Packers1`
    FOREIGN KEY (`Packers_id`)
    REFERENCES `mydb`.`Packers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Login` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Access` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`InventoryAccounting`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`InventoryAccounting` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Code` VARCHAR(45) NOT NULL,
  `TMC` VARCHAR(45) NOT NULL,
  `EdIzmer` VARCHAR(45) NOT NULL,
  `Kolichestvo` INT NOT NULL,
  `Cost` FLOAT NOT NULL,
  `Sum` FLOAT NOT NULL,
  `NP` VARCHAR(45) NOT NULL,
  `SumNp` FLOAT NOT NULL,
  `NDS` VARCHAR(45) NOT NULL,
  `SumNDS` FLOAT NOT NULL,
  `SumNDSandNP` FLOAT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CardStorageUchet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CardStorageUchet` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Period` DATE NOT NULL,
  `StorageLocation` VARCHAR(45) NOT NULL,
  `Materials` VARCHAR(45) NOT NULL,
  `Employee` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TMCInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TMCInfo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Period` DATE NOT NULL,
  `StorageLocation` VARCHAR(45) NOT NULL,
  `MOL` VARCHAR(45) NOT NULL,
  `Counterparties` VARCHAR(45) NOT NULL,
  `Employee` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RemainingStock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RemainingStock` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Code` VARCHAR(45) NULL,
  `Name` VARCHAR(45) NULL,
  `EdIzmer` VARCHAR(45) NULL,
  `Cost` FLOAT NULL,
  `RemainEndPer` VARCHAR(45) NULL,
  `Amount` INT NULL,
  `Sum` FLOAT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
